name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image for Backend
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .

    - name: Push Docker Image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

  deploy:
    needs: build
    runs-on: self-hosted[server]

    steps:
    - name: Pull Docker Image from Docker Hub
      run: docker pull ${{ secrets.DOCKER_USERNAME }}/backend:latest

    - name: Stop Existing Backend Container
      run: |
        docker stop banking-application-backend || true
        docker rm banking-application-backend || true

    - name: Run Backend Docker Container
      run: |
        docker run -d -p 5000:5000 --name banking-application-backend \
          -e MONGO_URI="${{ secrets.MONGO_URI }}" \
          -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
          ${{ secrets.DOCKER_USERNAME }}/backend:latest



