name: Backend CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image for Backend
      run: docker build -t anaseg/banking-application:backend-latest ./server

    - name: Push Docker Image to Docker Hub
      run: docker push anaseg/banking-application:backend-latest




